name: nixpkgs-update
version: 0.4.0
synopsis: Tool for semi-automatic updating of nixpkgs repository
description: nixpkgs-update provides tools for updating of nixpkgs
  packages in a semi-automatic way. Mainly, it is used to run the GitHub
  bot @r-ryantm, but the underlying update mechanisms should be
  generally useful and in a later version should be exposed as a
  command-line tool.
license: CC0-1.0
author: Ryan Mulligan et al.
maintainer: ryan@ryantm.com
copyright: 2018-2022 Ryan Mulligan et al.
category: Web
extra-source-files:
- README.md

github: nix-community/nixpkgs-update

ghc-options: -Wall -O2 -flate-specialise -fspecialise-aggressively -fplugin=Polysemy.Plugin

default-extensions:
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - BlockArguments

dependencies:
  - aeson
  - base >= 4.13 && < 5
  - bytestring
  - conduit
  - containers
  - cryptohash-sha256
  - directory
  - errors
  - filepath
  - github
  - http-client
  - http-client-tls
  - http-conduit
  - http-types
  - iso8601-time
  - lifted-base
  - mtl
  - neat-interpolation
  - optparse-applicative
  - parsec
  - parsers
  - partial-order
  - polysemy
  - polysemy-plugin
  - regex-applicative-text
  - servant
  - servant-client
  - sqlite-simple
  - template-haskell
  - temporary
  - text
  - th-env
  - time
  - transformers
  - typed-process
  - unix
  - unordered-containers
  - vector
  - versions
  - xdg-basedir
  - zlib

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_nixpkgs_update

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - hspec-discover
      - nixpkgs-update
      - doctest
    when:
      - condition: false
        other-modules: Paths_nixpkgs_update

executables:
  nixpkgs-update:
    source-dirs: app
    main: Main.hs
    dependencies:
      - nixpkgs-update
    when:
      - condition: false
        other-modules: Paths_nixpkgs_update
